# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NOTI_Teacher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NOTI_Teacher
  # Rx
  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod 'RxGesture', '< 4.1.0'
  pod 'RxDataSources', '<5.1.0'

  # Others
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Then'
  pod 'CircleProgressView', '~> 1.0'
end
